# Site settings
title: Ilham Gusti
email: ilham.wibowo51@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tema Situs Statik Buatan Ilham Gusti Wibowo Polar Blue
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ilhamgusti.github.io" # the base hostname & protocol for your site
twitter_username: ilhamgewew
github_username: ilhamgusti

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  header: "#00b2f0"
# Build settings #redcarpet, kramdown
highlighter: rouge
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: /post/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

kramdown:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]